### ISSUE TITLE
message.author.id is rounding the last 4 digits when adding to sheet

### ISSUE THREAD

**Issue by FunkedelicBob** [hugonun/discord2sheet-bot#1]
When a user sends a message it puts the data into the Google Sheet properly (username, user_id, time, user_message), but the message.author.id is rounding the last 4 digits... It's definitely not the spreadsheet as the field is formatted as plain text. I did "fix" this by formatting the message.author.id as a string `[str(message.author.id)]`... Still not sure why that's happening though.

Another user's ID:
xxxxxxxxxxxxx87880
Recording as:
xxxxxxxxxxxxx88000

My user id is:
xxxxxxxxxxxxx80865
Recording as:
xxxxxxxxxxxxx81000

**Comment by hugonun** [comment]
Thanks for reporting, I've fixed it.

The official Google Sheet's API wrapper seems to convert numbers (int) to floats, which has limitations and rounds it.
