### ISSUE TITLE
This app isn't verified

### ISSUE THREAD

**Issue by Palamedeus** [hugonun/discord2sheet-bot#2]
Ok so I replaced everything that I needed to, but when I attempt to run the app it gives me a screen saying

This app isn't verified
This app hasn't been verified by Google yet. Only proceed if you know and trust the developer.

If you’re the developer, submit a verification request to remove this screen. Learn more

How do I fix this?

**Comment by Lukemul6** [comment]
I got the same thing :(

**Comment by hugonun** [comment]
Do others have the same issue? I found this Stackoverflow thread, but it didn't happen to me: https://stackoverflow.com/questions/45437557/this-app-isnt-verified-this-app-hasnt-been-verified-by-google-yet-only-procee

**Comment by hugonun** [comment]
Could also be that the OATH client wasnt set as Desktop App.

![grafik](https://user-images.githubusercontent.com/43740923/102472558-b00ded80-4056-11eb-8add-5516fd30c26c.png)

**Comment by ACCISA** [comment]
I am having another type of issue. I placed everything into the right files, followed the procedure you gave. But I get this error.
![image](https://user-images.githubusercontent.com/39713625/123715152-b111aa00-d845-11eb-853e-dc15063faa7b.png)

**Comment by eldrago4** [comment]
Oh god, developer in the sense it's you who created the application, so if you make an OAuth2 application it's user-end which means you gotta authenticate ur account before using google services, and coming to the point even if you see app isn't verified screen, there's an option of 'advanced' below it so click on it and it allows you to proceed with authentication.
Also u can verify ur app by filling this [form](https://support.google.com/code/contact/oauth_app_verification).
![bjBX1](https://user-images.githubusercontent.com/63483703/124905443-a902f880-e003-11eb-8376-e942fcfddaf2.png)
