### ISSUE TITLE
Required Role Bug

### ISSUE THREAD

**Issue by noob04coder** [hugonun/discord2sheet-bot#4]
![image](https://user-images.githubusercontent.com/78252850/133386837-b9078d10-d1df-4d8a-92ea-78e73032be78.png)

First I tried without taking the role it said I dont have the role but even why I gave myself the required role it again showed the same message .

I think that parsing of required role as string is the issue becuase when I removed the string function it worked properly .
![image](https://user-images.githubusercontent.com/78252850/133387369-f40fb9d5-dffb-424c-a28a-9194d1c06ebe.png)

**Comment by noob04coder** [comment]
Another issue is that it replieas even to plain message without even the command 
![image](https://user-images.githubusercontent.com/78252850/133388189-fe313251-5d18-46a1-b4ea-bf75e9a08e8d.png)

and I think this can be solved by just adding another condition that is present in other commands i.e message.content.startswith('!s ')

**Comment by hugonun** [comment]
Thank you for the report, this has been fixed!
