### ISSUE TITLE
Code refuses to start at all

### ISSUE THREAD

**Issue by nnnagyb** [hugonun/discord2sheet-bot#6]
Can't say I know what's happening, everything's set up perfectly, as in, in worked for me for a while, shut down the bot for a month or so and now it just doesn't start back up. Couldn't find a solution

![image](https://user-images.githubusercontent.com/96133026/146031241-eb21b025-89a3-488b-808c-26a837df25e4.png)
Thanks in advance.

**Comment by hugonun** [comment]
It seems to be working on my side.

Have you tried getting a new credentials.json file?

**Comment by nnnagyb** [comment]
I can't exactly say what the error was caused by specifically, but a new oauth key and a py directory change solved it? I'm not exactly good at it but at least it works.
Thanks for responding, will close the thread now ig.
