### ISSUE TITLE
Error: You need to add 2 fields when using more than 2 fields

### ISSUE THREAD

**Issue by Yogogorilla** [hugonun/discord2sheet-bot#7]
Hi man,

First of all - huge thanks for the bot. it's awesome. 

I am getting an error when I am trying to include 4 fields. It's giving me an error saying I can only use 1 comma but it is uploading the data into the spreadsheet correctly.

Thanks agai
<img width="589" alt="Screen Shot 2022-02-21 at 9 45 48 pm" src="https://user-images.githubusercontent.com/100130259/154941326-5da92f26-6925-401a-a1cd-14278969a27a.png">
n

**Comment by hugonun** [comment]
Hello,

If you want to have 4fields, you will need to change the following line, which stores the amount of fields.

https://github.com/hugonun/discord2sheet-bot/blob/master/init.py#L25
